const examples={billing:"I was charged twice and support still has not responded.",technical:"The app crashes every time I try to upload a receipt.",positive:"I love the new dashboard. It is much easier to use.",feature:"I wish there were a way to export reports as CSV."};
let rows=[
{id:"F-1042",feedback:examples.billing,sentiment:"NEGATIVE",confidence:.97,category:"BILLING",severity:"HIGH",owner:"Billing Support",action:"Open priority case and request immediate human review",escalate:true},
{id:"F-1043",feedback:examples.technical,sentiment:"NEGATIVE",confidence:.94,category:"TECHNICAL",severity:"MEDIUM",owner:"Technical Support",action:"Create a technical support case with the reported error context",escalate:true},
{id:"F-1044",feedback:examples.positive,sentiment:"POSITIVE",confidence:.98,category:"GENERAL",severity:"LOW",owner:"General Support",action:"Monitor and include in customer feedback trends",escalate:false},
{id:"F-1045",feedback:examples.feature,sentiment:"NEUTRAL",confidence:.82,category:"FEATURE_REQUEST",severity:"LOW",owner:"Product Team",action:"Capture request for product review and trend analysis",escalate:false}
];
const any=(t,a)=>a.some(x=>t.includes(x));
function analyze(f){const t=f.toLowerCase();let sentiment="NEUTRAL",confidence=.78;if(any(t,["love","great","excellent","easy","helpful","happy"])){sentiment="POSITIVE";confidence=.91}else if(any(t,["charged","crash","error","broken","failed","cannot","can't","not responded","fraud","locked"])){sentiment="NEGATIVE";confidence=.90}
let category="GENERAL";if(any(t,["payment","charged","charge","billing","refund","invoice","card"]))category="BILLING";else if(any(t,["login","password","account","locked","sign in"]))category="ACCOUNT_ACCESS";else if(any(t,["crash","error","bug","broken","not working","failed","failure"]))category="TECHNICAL";else if(any(t,["support","agent","representative","response","wait","waiting"]))category="CUSTOMER_SUPPORT";else if(any(t,["feature","wish","suggest","improve","request","export"]))category="FEATURE_REQUEST";
let severity="LOW";if(any(t,["charged twice","charged three","multiple charges","fraud","locked out","cannot access","can't access","data loss","security","urgent"]))severity="HIGH";else if(sentiment==="NEGATIVE")severity="MEDIUM";
const owners={BILLING:"Billing Support",ACCOUNT_ACCESS:"Account Support",TECHNICAL:"Technical Support",CUSTOMER_SUPPORT:"Customer Success",FEATURE_REQUEST:"Product Team",GENERAL:"General Support"};
const actions={BILLING:"Review payment history and follow up with the customer",ACCOUNT_ACCESS:"Verify account status and initiate account recovery support",TECHNICAL:"Create a technical support case with the reported error context",CUSTOMER_SUPPORT:"Assign to Customer Success for follow-up",FEATURE_REQUEST:"Capture request for product review and trend analysis",GENERAL:"Monitor and include in customer feedback trends"};
const escalate=severity==="HIGH"||(sentiment==="NEGATIVE"&&severity==="MEDIUM");return{id:`F-${1046+rows.length}`,feedback:f,sentiment,confidence,category,severity,owner:owners[category],action:severity==="HIGH"?"Open priority case and request immediate human review":actions[category],escalate}}
function render(){const vals=[["Feedback processed",rows.length],["Negative sentiment",rows.filter(r=>r.sentiment==="NEGATIVE").length],["High priority",rows.filter(r=>r.severity==="HIGH").length],["Needs human review",rows.filter(r=>r.escalate).length]];document.querySelector("#metrics").innerHTML=vals.map(v=>`<div class="metric"><span>${v[0]}</span><b>${v[1]}</b></div>`).join("");
const q=rows.filter(r=>r.escalate);document.querySelector("#count").textContent=`${q.length} open`;document.querySelector("#queue").innerHTML=q.map(r=>`<div class="queue-card"><b>${r.category.replaceAll("_"," ")}</b> <span class="pill ${r.severity.toLowerCase()}">${r.severity}</span><p>${r.feedback}</p><small>${r.owner} · ${(r.confidence*100).toFixed(0)}% sentiment confidence</small></div>`).join("")||"<p>No cases need review.</p>";
document.querySelector("#table").innerHTML=[...rows].reverse().map(r=>`<tr><td>${r.id}</td><td>${r.feedback}</td><td><span class="pill ${r.sentiment.toLowerCase()}">${r.sentiment}</span></td><td>${(r.confidence*100).toFixed(0)}%</td><td>${r.category.replaceAll("_"," ")}</td><td><span class="pill ${r.severity.toLowerCase()}">${r.severity}</span></td><td>${r.owner}</td><td>${r.action}</td></tr>`).join("")}
document.querySelectorAll("[data-example]").forEach(b=>b.addEventListener("click",()=>document.querySelector("#input").value=examples[b.dataset.example]));
document.querySelector("#analyze").addEventListener("click",()=>{const f=document.querySelector("#input").value.trim();if(!f)return;const r=analyze(f);rows.push(r);document.querySelector("#result").innerHTML=`<div class="result"><div class="result-grid"><div><span>Sentiment</span><b>${r.sentiment}</b></div><div><span>Confidence</span><b>${(r.confidence*100).toFixed(0)}%</b></div><div><span>Category</span><b>${r.category.replaceAll("_"," ")}</b></div><div><span>Severity</span><b>${r.severity}</b></div><div><span>Recommended owner</span><b>${r.owner}</b></div><div><span>Human review</span><b>${r.escalate?"Required":"Not required"}</b></div></div><div class="action"><b>Recommended action:</b> ${r.action}</div></div>`;render()});
render();